excluded:
    - ../App/SwiftGithubTrend/Resources
    - ../App/Pods
disabled_rules:
    - trailing_comma
    - line_length
opt_in_rules:
    - yoda_condition
    - unused_import
    - unused_declaration
    - unavailable_function
    - empty_string
    - empty_collection_literal
    - empty_count
    - enum_case_associated_values_count
    - explicit_self
    - fatal_error_message
    - file_name_no_space
    - attributes
    - discouraged_object_literal
    - discouraged_optional_boolean
    - file_header
    - file_name
    - file_types_order
    - force_unwrapping
    - implicitly_unwrapped_optional
    - indentation_width
    - multiline_arguments
    - multiline_literal_brackets
    - multiline_parameters
    - private_action
    - private_outlet
    - private_subject
    - redundant_type_annotation

